version: '3.8'

services:
  mcp-server:
    build:
      context: ./docker/mcp-server
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/mcp
      - ./deployment:/var/deployment
    networks:
      - mcp-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MCP_SERVER_PORT=8080
      - NODE_ENV=production

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    networks:
      - mcp-network
    restart: always
    depends_on:
      - mcp-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  react-app:
    build:
      context: ./docker/react-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - ./03_sample_projects/react_apps:/app
      - node_modules:/app/node_modules
    networks:
      - mcp-network
    restart: always
    environment:
      - NODE_ENV=development
      - VITE_MCP_SERVER_URL=http://mcp-server:8080
    depends_on:
      - mcp-server

  deployment-manager:
    build:
      context: ./docker/deployment
      dockerfile: Dockerfile
    container_name: deployment-manager
    volumes:
      - ./02_deployment_tools:/app
      - ./deployment:/var/deployment
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mcp-network
    restart: always
    depends_on:
      - mcp-server
    environment:
      - MCP_SERVER_URL=http://mcp-server:8080

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  node_modules:
    driver: local
  nginx_logs:
    driver: local
  mcp_logs:
    driver: local