version: '3.8'

services:
  mcp-server:
    build:
      context: ./docker-enhanced/mcp-server
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/mcp
      - ./deployment:/var/deployment
    networks:
      - mcp-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MCP_SERVER_PORT=8080
      - NODE_ENV=production

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-nginx-app
    ports:
      - "80:3000"
    networks:
      - mcp-network
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_MCP_SERVER_URL=http://192.168.111.200:8080
    depends_on:
      - mcp-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  deployment-manager:
    build:
      context: ./docker-enhanced/deployment
      dockerfile: Dockerfile
    container_name: deployment-manager
    volumes:
      - ./scripts:/app/scripts
      - ./deployment:/var/deployment
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mcp-network
    restart: always
    depends_on:
      - mcp-server
    environment:
      - MCP_SERVER_URL=http://mcp-server:8080
    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  mcp_logs:
    driver: local
  deployment_data:
    driver: local